apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: chatbot1-oct16-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  chatbot1-oct16-1
    app.kubernetes.io/part-of: chatbot1-oct16-1  
  name: chatbot1-oct16-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  chatbot1-oct16-1 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  chatbot1-oct16-1
    spec:
      containers:
      - image:  quay.io/redhat-ai-dev/ai-template-bootstrap-app:latest
        name: app-inference
        envFrom:
        - configMapRef:
            name: chatbot1-oct16-1-model-config
        env:
        - name: MODEL_ENDPOINT_BEARER
          valueFrom:
            secretKeyRef:
              name: ibm-granite-8b-app
              key: api_key
        ports:
        - containerPort: 8501
        securityContext:
          runAsNonRoot: true
